#!/usr/bin/env python3
"""
Generate chat/template.yaml from chat/.sam-config (and chat/.env.local metadata).

Mirrors backend/scripts/generate_template.py, scoped to the chat service:
- .sam-config: stack + Lambda + Function URL + CORS metadata
- .env.local:  (future) secret env-var metadata via _PARAM_NAME / _PROD_VALUE
               comments — none in Phase 6A.

Output:
- chat/template.yaml: SAM template for the chat Function URL (jh-chat-stack)

Exit codes (consumed by jpushchat): 0 = no change, 1 = modified, 2 = created.

DO NOT hand-edit chat/template.yaml — edit chat/.sam-config and regenerate.
"""

import os
import re
import sys
from pathlib import Path


def parse_env_file(filepath):
    """Parse key=value lines, ignoring comments/blanks."""
    config = {}
    if not os.path.exists(filepath):
        return config
    with open(filepath, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, value = line.split("=", 1)
                config[key.strip()] = value.strip()
    return config


def parse_env_local_param_metadata(filepath):
    """
    Extract CloudFormation parameter metadata from chat/.env.local comments.

    For each UPPER_CASE var, reads adjacent comments:
      # VAR_PARAM_NAME = CfnParamName
      # VAR_DESCRIPTION = ...
      # VAR_NO_ECHO = true|false
    Returns list of dicts: {param_name, description, no_echo}.
    None expected in Phase 6A (no secret env vars yet).
    """
    if not os.path.exists(filepath):
        return []
    meta = {}
    current = None
    with open(filepath, "r") as f:
        for line in f:
            line = line.strip()
            if "=" in line and not line.startswith("#"):
                name = line.split("=", 1)[0].strip()
                if name.isupper():
                    current = name
                    meta.setdefault(current, {})
            if line.startswith("#") and current:
                m = re.match(r"#\s*([A-Z_]+)_PARAM_NAME\s*=\s*(.+)", line)
                if m and m.group(1) == current:
                    meta[current]["PARAM_NAME"] = m.group(2).strip()
                m = re.match(r"#\s*([A-Z_]+)_DESCRIPTION\s*=\s*(.+)", line)
                if m and m.group(1) == current:
                    meta[current]["DESCRIPTION"] = m.group(2).strip()
                m = re.match(r"#\s*([A-Z_]+)_NO_ECHO\s*=\s*(.+)", line)
                if m and m.group(1) == current:
                    meta[current]["NO_ECHO"] = m.group(2).strip().lower() == "true"
    params = []
    for var, md in meta.items():
        if "PARAM_NAME" in md:
            params.append(
                {
                    "env_var": var,  # the env var the handler reads (e.g. SECRET_KEY)
                    "param_name": md["PARAM_NAME"],  # the CFN param (e.g. JWTSecretKey)
                    "description": md.get("DESCRIPTION", ""),
                    "no_echo": md.get("NO_ECHO", False),
                }
            )
    return params


def generate_template_yaml(cfg, extra_params, static_env_vars):
    """Build the chat template.yaml content."""
    fn_name = cfg.get("CHAT_FUNCTION_NAME", "JobHuntChat")
    fn_desc = cfg.get("CHAT_FUNCTION_DESCRIPTION", "Chat service")
    handler = cfg.get("CHAT_HANDLER", "handler.handler")
    runtime = cfg.get("CHAT_RUNTIME", "nodejs22.x")
    timeout = cfg.get("CHAT_TIMEOUT", "300")
    memory = cfg.get("CHAT_MEMORY", "256")
    code_uri = cfg.get("CHAT_CODE_URI", ".")
    auth = cfg.get("CHAT_FUNCTION_URL_AUTH", "NONE")
    invoke_mode = cfg.get("CHAT_FUNCTION_URL_INVOKE_MODE", "RESPONSE_STREAM")
    cors_origins = cfg.get(
        "CHAT_CORS_ALLOW_ORIGINS", "http://localhost:3000,https://zduan-job.vercel.app"
    )

    lines = [
        "AWSTemplateFormatVersion: '2010-09-09'",
        "Transform: AWS::Serverless-2016-10-31",
        "Description: Streaming chat service (Node.js) for Job Hunt Tracker",
        "",
        "# GENERATED by chat/scripts/generate_template.py from chat/.sam-config.",
        "# DO NOT hand-edit — edit chat/.sam-config and run the generator (or jpushchat).",
        "#",
        "# Own stack (jh-chat-stack), separate from the Python backend:",
        "# different runtime, Function URL + RESPONSE_STREAM, independent lifecycle.",
        "# See ADR-025 (runtime) and ADR-030 (topology).",
        "",
        "Parameters:",
        "  AllowedOrigins:",
        "    Type: CommaDelimitedList",
        "    Description: CORS allowed origins for the chat Function URL",
        f'    Default: "{cors_origins}"',
    ]

    # Future secret params (from .env.local metadata) — none in 6A.
    for p in extra_params:
        lines.append(f"  {p['param_name']}:")
        lines.append("    Type: String")
        if p["description"]:
            lines.append(f"    Description: {p['description']}")
        lines.append(f"    NoEcho: {'true' if p['no_echo'] else 'false'}")

    lines += [
        "",
        "Resources:",
        "  ChatFunction:",
        "    Type: AWS::Serverless::Function",
        "    Properties:",
        f"      FunctionName: {fn_name}",
        f"      CodeUri: {code_uri}",
        f"      Handler: {handler}",
        f"      Runtime: {runtime}",
        f"      Timeout: {timeout}",
        f"      MemorySize: {memory}",
        f"      Description: {fn_desc}",
        "      FunctionUrlConfig:",
        f"        AuthType: {auth}",
        f"        InvokeMode: {invoke_mode}",
        "        Cors:",
        "          AllowOrigins: !Ref AllowedOrigins",
        "          AllowMethods:",
        "            - POST",
        "            - GET",
        "          AllowHeaders:",
        '            - "*"',
    ]

    # Function environment: static (non-secret) vars + secret-param refs.
    if static_env_vars or extra_params:
        lines.append("      Environment:")
        lines.append("        Variables:")
        for name in sorted(static_env_vars.keys()):
            lines.append(f"          {name}: {static_env_vars[name]}")
        for p in extra_params:
            # Env var name = the env_var the handler reads (e.g. SECRET_KEY),
            # value = a ref to the CloudFormation parameter (e.g. JWTSecretKey).
            lines.append(f"          {p['env_var']}: !Ref {p['param_name']}")

    lines += [
        "",
        "Outputs:",
        "  ChatFunctionUrl:",
        "    Description: Chat streaming Function URL (set CHAT_AWS_URL to this for jchat-test --aws)",
        "    Value: !GetAtt ChatFunctionUrl.FunctionUrl",
        "",
        "  ChatFunctionName:",
        "    Description: Chat Lambda function name",
        "    Value: !Ref ChatFunction",
        "",
    ]
    return "\n".join(lines)


def main():
    chat_dir = Path(__file__).parent.parent
    cfg = parse_env_file(chat_dir / ".sam-config")
    extra_params = parse_env_local_param_metadata(chat_dir / ".env.local")
    # Static (non-secret) env vars: ENV_VAR_<NAME> in .sam-config → <NAME> on Lambda.
    static_env_vars = {
        k[len("ENV_VAR_"):]: v for k, v in cfg.items() if k.startswith("ENV_VAR_")
    }
    new_content = generate_template_yaml(cfg, extra_params, static_env_vars)

    template_path = chat_dir / "template.yaml"
    if template_path.exists():
        existing = template_path.read_text()
        if existing == new_content:
            print("✓ chat/template.yaml (no changes)")
            sys.exit(0)
        template_path.write_text(new_content)
        print("⚠ chat/template.yaml modified")
        sys.exit(1)
    template_path.write_text(new_content)
    print("⚠ chat/template.yaml created (new file)")
    sys.exit(2)


if __name__ == "__main__":
    main()
