AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI backend for Job Hunt Tracker

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.13
    Environment:
      Variables:
        ALLOWED_EMAILS: !Ref AllowedEmails
        ALLOWED_ORIGINS: !Ref AllowedOrigins
        DATABASE_URL: !Ref DatabaseUrl
        GOOGLE_CLIENT_ID: !Ref GoogleClientId
        SECRET_KEY: !Ref JWTSecretKey
        TEST_DATABASE_URL: !Ref TestDatabaseUrl
        ACCESS_TOKEN_EXPIRE_MINUTES: 1440
        ALGORITHM: HS256
        GOOGLE_CLIENT_SECRET: optional-for-token-validation

Parameters:
  AllowedEmails:
    Type: String
    Description: Comma-separated list of allowed user emails
    NoEcho: false
    Default: "zduanx@gmail.com"

  AllowedOrigins:
    Type: String
    Description: Comma-separated list of allowed CORS origins
    NoEcho: false
    Default: "http://localhost:3000,http://localhost:5173"

  DatabaseUrl:
    Type: String
    Description: PostgreSQL database connection URL (production branch)
    NoEcho: true

  GoogleClientId:
    Type: String
    Description: Google OAuth Client ID
    NoEcho: false

  JWTSecretKey:
    Type: String
    Description: Secret key for JWT signing (use openssl rand -hex 32)
    NoEcho: true

  TestDatabaseUrl:
    Type: String
    Description: PostgreSQL test database connection URL (for testing SQS/Lambda)
    NoEcho: true

Resources:

  # ==========================================================================
  # API Lambda - HTTP endpoints via API Gateway
  # ==========================================================================
  JobHuntTrackerAPI:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: JobHuntTrackerAPI
      CodeUri: .
      Handler: main.handler
      Description: FastAPI backend for Job Hunt Tracker
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref IngestionWorker
      Environment:
        Variables:
          WORKER_FUNCTION_NAME: !Ref IngestionWorker
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref HttpApi
        RootEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
            ApiId: !Ref HttpApi

  # ==========================================================================
  # Worker Lambda - Async invoke for long-running ingestion (15 min timeout)
  # ==========================================================================
  IngestionWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: IngestionWorker
      CodeUri: .
      Handler: workers.ingestion_worker.handler
      Description: Async worker for job ingestion (15 min timeout)
      Timeout: 900
      MemorySize: 512
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt CrawlerQueue.QueueName
      Environment:
        Variables:
          CRAWLER_QUEUE_URL: !Ref CrawlerQueue
      # No Events - invoked async by API Lambda, not by HTTP

  # ==========================================================================
  # Crawler Queue - FIFO queue for per-company rate limiting
  # ==========================================================================
  CrawlerQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: CrawlerQueue.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 180  # 3 retries × ~30s crawl + overhead
      MessageRetentionPeriod: 86400  # 1 day
      # No DLQ - crawler handles retries internally and marks failures in DB

  # ==========================================================================
  # Raw Content Bucket - S3 storage for crawled HTML
  # ==========================================================================
  RawContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "jh-raw-content-${AWS::AccountId}"
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldContent
            Status: Enabled
            ExpirationInDays: 30  # Raw HTML only needed temporarily

  # ==========================================================================
  # Crawler Worker Lambda - SQS-triggered for crawling job pages
  # ==========================================================================
  CrawlerWorker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CrawlerWorker
      CodeUri: .
      Handler: workers.crawler_worker.handler
      Description: SQS-triggered worker for crawling job pages
      Timeout: 120
      MemorySize: 512
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref RawContentBucket
      Environment:
        Variables:
          RAW_BUCKET: !Ref RawContentBucket
          CRAWLER_QUEUE_URL: !Ref CrawlerQueue
      Events:
        CrawlerQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt CrawlerQueue.Arn
            BatchSize: 1
            Enabled: true

  # ==========================================================================
  # API Gateway
  # ==========================================================================
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - "http://localhost:3000"
          - "https://zduan-job.vercel.app"
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowCredentials: true

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod"

  FunctionName:
    Description: API Lambda function name
    Value: !Ref JobHuntTrackerAPI

  WorkerFunctionName:
    Description: Worker Lambda function name
    Value: !Ref IngestionWorker

  CrawlerQueueUrl:
    Description: Crawler SQS FIFO queue URL
    Value: !Ref CrawlerQueue

  CrawlerWorkerFunctionName:
    Description: Crawler Worker Lambda function name
    Value: !Ref CrawlerWorker

  RawContentBucketName:
    Description: S3 bucket for raw crawled content
    Value: !Ref RawContentBucket
